# Mouse support
set -g mouse on

# Vi copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "wl-copy"

# Quick edit in clipboard
bind-key e capture-pane -S -3000 \; save-buffer /tmp/tmux-buffer.txt \; delete-buffer \; new-window "hx /tmp/tmux-buffer.txt"

# Improve colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Status bar
set -g status-bg colour235
set -g status-fg white
set -g status-interval 5
set -g status-left '#[fg=green]#S '

# History
set -g history-limit 50000

# Start index at 1 (not 0)
set -g base-index 1
setw -g pane-base-index 1

# Reload config
bind r source-file /etc/tmux.conf \; display "Config reloaded"

# TTAL project sessions
bind P display-popup -E "@ttalTmuxProjectPicker@"
bind R command-prompt -I "#S" -p "Rename session:" "rename-session '%%'"

# Default shell
set-option -g default-shell /run/current-system/sw/bin/fish

# Override EDITOR for headless NixOS
set-environment -g EDITOR hx
